name: "hubert"
platform: "onnxruntime_onnx"
max_batch_size: 32
input [
  {
    name: "input_values"
    data_type: TYPE_FP32
    dims: [ -1 ]  # batch x length
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]

instance_group [
  {
    kind: KIND_GPU
    count: 1
    gpus: [0]
  }
]

dynamic_batching {
  preferred_batch_size: [ 4, 8, 16 ]
  max_queue_delay_microseconds: 1000
}